dato1 = None    # Null
dato2 = 1       # Entero
dato3 = 1.3     # Decimal
dato4 = True    # Booleano
dato6 = "Soy un texto"  # Cadena de texto
dato5 = 3 + 4j  # Complejo
dato7 = (1,2)   # Tupla
dato8 = [1,2]   # Lista
dato9 = {1,2}   # Set (Conjunto)
dato10= {"1":"A", "2":"B"}  # Diccionario