# Generated by Django 5.1.6 on 2025-03-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=6)),
                ('anio', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=25)),
                ('transmision', models.CharField(choices=[('A', 'Automático'), ('M', 'Mecánico')], max_length=15)),
                ('combustible', models.CharField(choices=[('P', 'GLP'), ('V', 'GNV'), ('G', 'Gasolina'), ('D', 'Diesel'), ('E', 'Electricidad')], max_length=15)),
                ('portada', models.CharField(choices=[('0', 'No'), ('1', 'Sí')], default='0', max_length=1)),
            ],
        ),
    ]
