# Generated by Django 5.1.6 on 2025-03-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
