"""agregamos descripcion a productos

Revision ID: afef50bf38ca
Revises: 94b39714a7e2
Create Date: 2025-02-20 22:47:02.221508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afef50bf38ca'
down_revision = '94b39714a7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
